<a href="https://colab.research.google.com/github/ruthikaraja08/ruthika/blob/main/bankstring.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/drive/MyDrive/bank_customer_data.csv")

In [3]:
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city
0,SANthosh Chevuri,SANTHOSH@GMAIL.COM,hdfc bank,savings,ACC-1001,"Rs 1,25,000",hyderabad
1,RAJU kumar,RAJU@YAHOO.COM,ICICI BANK,CURRENT,ACC-1002,"$2,500",VIJAYAWADA
2,kiran REDDY,KIRAN@GMAIL.COM,axis bank,salary,ACC-1003,"Rs 75,000",vizag
3,SURESH BABU,SURESH@OUTLOOK.COM,SBI,SAVINGS,ACC-1004,"$10,000",GUNTUR
4,Lakshmi devi,LAKSHMI@GMAIL.COM,kotak bank,current,ACC-1005,"Rs 50,500",tirupati

In [6]:
df["customer_name"]=df["customer_name"].str.title()
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city
0,Santhosh Chevuri,SANTHOSH@GMAIL.COM,hdfc bank,savings,ACC-1001,"Rs 1,25,000",hyderabad
1,Raju Kumar,RAJU@YAHOO.COM,ICICI BANK,CURRENT,ACC-1002,"$2,500",VIJAYAWADA
2,Kiran Reddy,KIRAN@GMAIL.COM,axis bank,salary,ACC-1003,"Rs 75,000",vizag
3,Suresh Babu,SURESH@OUTLOOK.COM,SBI,SAVINGS,ACC-1004,"$10,000",GUNTUR
4,Lakshmi Devi,LAKSHMI@GMAIL.COM,kotak bank,current,ACC-1005,"Rs 50,500",tirupati

In [7]:
df["email"]=df["email"].str.lower()
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city
0,Santhosh Chevuri,santhosh@gmail.com,hdfc bank,savings,ACC-1001,"Rs 1,25,000",hyderabad
1,Raju Kumar,raju@yahoo.com,ICICI BANK,CURRENT,ACC-1002,"$2,500",VIJAYAWADA
2,Kiran Reddy,kiran@gmail.com,axis bank,salary,ACC-1003,"Rs 75,000",vizag
3,Suresh Babu,suresh@outlook.com,SBI,SAVINGS,ACC-1004,"$10,000",GUNTUR
4,Lakshmi Devi,lakshmi@gmail.com,kotak bank,current,ACC-1005,"Rs 50,500",tirupati

In [8]:
df["bank_name"]=df["bank_name"].str.upper()
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city
0,Santhosh Chevuri,santhosh@gmail.com,HDFC BANK,savings,ACC-1001,"Rs 1,25,000",hyderabad
1,Raju Kumar,raju@yahoo.com,ICICI BANK,CURRENT,ACC-1002,"$2,500",VIJAYAWADA
2,Kiran Reddy,kiran@gmail.com,AXIS BANK,salary,ACC-1003,"Rs 75,000",vizag
3,Suresh Babu,suresh@outlook.com,SBI,SAVINGS,ACC-1004,"$10,000",GUNTUR
4,Lakshmi Devi,lakshmi@gmail.com,KOTAK BANK,current,ACC-1005,"Rs 50,500",tirupati

In [9]:
df["account_type"]=df["account_type"].str.upper()
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city
0,Santhosh Chevuri,santhosh@gmail.com,HDFC BANK,SAVINGS,ACC-1001,"Rs 1,25,000",hyderabad
1,Raju Kumar,raju@yahoo.com,ICICI BANK,CURRENT,ACC-1002,"$2,500",VIJAYAWADA
2,Kiran Reddy,kiran@gmail.com,AXIS BANK,SALARY,ACC-1003,"Rs 75,000",vizag
3,Suresh Babu,suresh@outlook.com,SBI,SAVINGS,ACC-1004,"$10,000",GUNTUR
4,Lakshmi Devi,lakshmi@gmail.com,KOTAK BANK,CURRENT,ACC-1005,"Rs 50,500",tirupati

In [10]:
df["balance"]=df["balance"].str.replace("Rs ","", regex= False)
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city
0,Santhosh Chevuri,santhosh@gmail.com,HDFC BANK,SAVINGS,ACC-1001,"1,25,000",hyderabad
1,Raju Kumar,raju@yahoo.com,ICICI BANK,CURRENT,ACC-1002,"$2,500",VIJAYAWADA
2,Kiran Reddy,kiran@gmail.com,AXIS BANK,SALARY,ACC-1003,"75,000",vizag
3,Suresh Babu,suresh@outlook.com,SBI,SAVINGS,ACC-1004,"$10,000",GUNTUR
4,Lakshmi Devi,lakshmi@gmail.com,KOTAK BANK,CURRENT,ACC-1005,"50,500",tirupati

In [22]:
df["balance"]=df["balance"].str.replace("$","", regex= False)
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city,username,domain,branch_code
0,Santhosh Chevuri,santhosh@gmail.com,HDFC BANK,SAVINGS,1001,125000,hyderabad,santhosh,"[santhosh, gmail.com]",hyd
1,Raju Kumar,raju@yahoo.com,ICICI BANK,CURRENT,1002,2500,VIJAYAWADA,raju,"[raju, yahoo.com]",VIJ
2,Kiran Reddy,kiran@gmail.com,AXIS BANK,SALARY,1003,75000,vizag,kiran,"[kiran, gmail.com]",viz
3,Suresh Babu,suresh@outlook.com,SBI,SAVINGS,1004,10000,GUNTUR,suresh,"[suresh, outlook.com]",GUN
4,Lakshmi Devi,lakshmi@gmail.com,KOTAK BANK,CURRENT,1005,50500,tirupati,lakshmi,"[lakshmi, gmail.com]",tir

In [21]:
df["balance"]=df["balance"].str.replace(",","", regex= False)
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city,username,domain,branch_code
0,Santhosh Chevuri,santhosh@gmail.com,HDFC BANK,SAVINGS,1001,125000,hyderabad,santhosh,"[santhosh, gmail.com]",hyd
1,Raju Kumar,raju@yahoo.com,ICICI BANK,CURRENT,1002,$2500,VIJAYAWADA,raju,"[raju, yahoo.com]",VIJ
2,Kiran Reddy,kiran@gmail.com,AXIS BANK,SALARY,1003,75000,vizag,kiran,"[kiran, gmail.com]",viz
3,Suresh Babu,suresh@outlook.com,SBI,SAVINGS,1004,$10000,GUNTUR,suresh,"[suresh, outlook.com]",GUN
4,Lakshmi Devi,lakshmi@gmail.com,KOTAK BANK,CURRENT,1005,50500,tirupati,lakshmi,"[lakshmi, gmail.com]",tir

In [28]:
df["balance"]=df['balance'].astype(int)
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city,username,domain,branch_code
0,Santhosh Chevuri,santhosh@gmail.com,HDFC BANK,SAVINGS,1001,125000,hyderabad,santhosh,"[santhosh, gmail.com]",hyd
1,Raju Kumar,raju@yahoo.com,ICICI BANK,CURRENT,1002,2500,VIJAYAWADA,raju,"[raju, yahoo.com]",VIJ
2,Kiran Reddy,kiran@gmail.com,AXIS BANK,SALARY,1003,75000,vizag,kiran,"[kiran, gmail.com]",viz
3,Suresh Babu,suresh@outlook.com,SBI,SAVINGS,1004,10000,GUNTUR,suresh,"[suresh, outlook.com]",GUN
4,Lakshmi Devi,lakshmi@gmail.com,KOTAK BANK,CURRENT,1005,50500,tirupati,lakshmi,"[lakshmi, gmail.com]",tir

In [ ]:
df["username"]=df["email"].str.split("@").str[0]
df

In [ ]:
df["domain"]=df["email"].str.split("@")
df

In [ ]:
df["branch_code"]=df["branch_city"].str[:3]
df

In [ ]:
df["account_number"]=df["account_number"].str.removeprefix("ACC-")
df