<a href="https://colab.research.google.com/github/ruthikaraja08/ruthika/blob/main/concat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
india_weather=pd.DataFrame({
    "city" : ["mumbai", "delhi", "bangalore"],
    "temp" : [30,35,40],
    "humidity" : [80,90,75]
    })
print(india_weather)

        city  temp  humidity
0     mumbai    30        80
1      delhi    35        90
2  bangalore    40        75

In [5]:
paris_weather=pd.DataFrame(
    {
        "city" : ["paris", "london", "newyork"],
        "temp" : [30,35,40],
        "humidity" : [80,90,75]
    }
)
print(paris_weather)

      city  temp  humidity
0    paris    30        80
1   london    35        90
2  newyork    40        75

In [8]:
df=pd.concat([india_weather,paris_weather])
df

        city  temp  humidity
0     mumbai    30        80
1      delhi    35        90
2  bangalore    40        75
0      paris    30        80
1     london    35        90
2    newyork    40        75

In [7]:
df=pd.concat([india_weather,paris_weather],axis=1)
df

        city  temp  humidity     city  temp  humidity
0     mumbai    30        80    paris    30        80
1      delhi    35        90   london    35        90
2  bangalore    40        75  newyork    40        75

In [9]:
df=pd.concat([india_weather,paris_weather],ignore_index=True)
df

        city  temp  humidity
0     mumbai    30        80
1      delhi    35        90
2  bangalore    40        75
3      paris    30        80
4     london    35        90
5    newyork    40        75

In [10]:
df=pd.concat([india_weather,paris_weather], keys=["ind", "paris"])
df

              city  temp  humidity
ind   0     mumbai    30        80
      1      delhi    35        90
      2  bangalore    40        75
paris 0      paris    30        80
      1     london    35        90
      2    newyork    40        75