<a href="https://colab.research.google.com/github/ruthikaraja08/ruthika/blob/main/datacleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/student_data_cleaning.csv")
df

  Student Name    Age          City  Marks   Join Date
0         Ram    20.0           HYD   85.0  2024-01-10
1         Ravi    NaN     Hyderabad   90.0  2024-02-15
2        Kumar   22.0           hyd    NaN  2024/03/20
3         Ram    20.0           HYD   85.0  2024-01-10
4         John  150.0   Vijayawada    95.0  2024-04-25
5          NaN   21.0           HYD   88.0  2024-05-01

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student Name  5 non-null      object
 1   Age           5 non-null      float64
 2   City          6 non-null      object
 3   Marks         5 non-null      float64
 4   Join Date     6 non-null      object
dtypes: float64(2), object(3)
memory usage: 372.0+ bytes

In [3]:
df["Age"]=df["Age"].fillna(df["Age"].mean())
df
df["Marks"]=df["Marks"].fillna(df["Marks"].mean())
df

  Student Name    Age          City  Marks   Join Date
0         Ram    20.0           HYD   85.0  2024-01-10
1         Ravi   46.6     Hyderabad   90.0  2024-02-15
2        Kumar   22.0           hyd   88.6  2024/03/20
3         Ram    20.0           HYD   85.0  2024-01-10
4         John  150.0   Vijayawada    95.0  2024-04-25
5          NaN   21.0           HYD   88.0  2024-05-01

In [4]:
df.duplicated().sum()

np.int64(0)

In [6]:
df=df.drop_duplicates(df)

In [7]:
df

  Student Name    Age          City  Marks   Join Date
0         Ram    20.0           HYD   85.0  2024-01-10
1         Ravi   46.6     Hyderabad   90.0  2024-02-15
2        Kumar   22.0           hyd   88.6  2024/03/20
3         Ram    20.0           HYD   85.0  2024-01-10
4         John  150.0   Vijayawada    95.0  2024-04-25
5          NaN   21.0           HYD   88.0  2024-05-01

In [10]:
df["City"]=df["City"].replace(
    {
        "HYD":"Hyderabad",
        "hyd":"Hyderabad"
    }
)
df

  Student Name    Age          City  Marks   Join Date
0         Ram    20.0     Hyderabad   85.0  2024-01-10
1         Ravi   46.6     Hyderabad   90.0  2024-02-15
2        Kumar   22.0     Hyderabad   88.6  2024/03/20
3         Ram    20.0     Hyderabad   85.0  2024-01-10
4         John  150.0   Vijayawada    95.0  2024-04-25
5          NaN   21.0     Hyderabad   88.0  2024-05-01

In [12]:
df.columns=(
    df.columns.str.lower().str.replace(" ","_")
)
df

  student_name    age          city  marks   join_date
0         Ram    20.0     Hyderabad   85.0  2024-01-10
1         Ravi   46.6     Hyderabad   90.0  2024-02-15
2        Kumar   22.0     Hyderabad   88.6  2024/03/20
3         Ram    20.0     Hyderabad   85.0  2024-01-10
4         John  150.0   Vijayawada    95.0  2024-04-25
5          NaN   21.0     Hyderabad   88.0  2024-05-01

In [14]:
df["join_date"]=pd.to_datetime(
    df["join_date"],
    format="mixed"
)
df

  student_name    age          city  marks  join_date
0         Ram    20.0     Hyderabad   85.0 2024-01-10
1         Ravi   46.6     Hyderabad   90.0 2024-02-15
2        Kumar   22.0     Hyderabad   88.6 2024-03-20
3         Ram    20.0     Hyderabad   85.0 2024-01-10
4         John  150.0   Vijayawada    95.0 2024-04-25
5          NaN   21.0     Hyderabad   88.0 2024-05-01