<a href="https://colab.research.google.com/github/ruthikaraja08/ruthika/blob/main/datatimehandling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/transaction_data.csv")
df

In [ ]:
df.info()

In [ ]:
df["transaction_date"]=pd.to_datetime(
    df["transaction_date"]
)
df.info()

In [ ]:
df["transaction_time"]=pd.to_datetime(
    df["transaction_time"]
)
df.info()

In [ ]:
df["transaction_datetime"]=pd.to_datetime(
    df["transaction_datetime"]
)
df.info()

In [ ]:
df

In [ ]:
df["year"]=df["transaction_date"].dt.year
df

In [ ]:
df["month"]=df["transaction_date"].dt.month
df

In [ ]:
df["day"]=df["transaction_date"].dt.day
df

In [ ]:
df["month_name"]=df["transaction_date"].dt.month_name()
df

In [ ]:
df["day_name"]=df["transaction_date"].dt.day_name()
df

In [15]:
#extract quarter
df["quarter"]=df["transaction_date"].dt.quarter
df

,customer_name,transaction_date,transaction_time,transaction_datetime,amount,year,month,day,month_name,day_name,quarter
0,Santhosh,2024-01-15,2026-05-30 09:30:45,2024-01-15 09:30:45,1000,2024,1,15,January,Monday,1
1,Raju,2024-03-22,2026-05-30 14:15:20,2024-03-22 14:15:20,2500,2024,3,22,March,Friday,1
2,Kiran,2024-06-10,2026-05-30 18:45:10,2024-06-10 18:45:10,1800,2024,6,10,June,Monday,2
3,Suresh,2024-09-05,2026-05-30 11:20:35,2024-09-05 11:20:35,3200,2024,9,5,September,Thursday,3
4,Lakshmi,2024-12-18,2026-05-30 22:10:05,2024-12-18 22:10:05,1500,2024,12,18,December,Wednesday,4

In [18]:
df["hour"]=df["transaction_datetime"].dt.hour
df["minutes"]=df["transaction_datetime"].dt.minute
df["seconds"]=df["transaction_datetime"].dt.second
df["date"]=df["transaction_datetime"].dt.date
df

,customer_name,transaction_date,transaction_time,transaction_datetime,amount,year,month,day,month_name,day_name,quarter,hour,minutes,seconds,date
0,Santhosh,2024-01-15,2026-05-30 09:30:45,2024-01-15 09:30:45,1000,2024,1,15,January,Monday,1,9,30,45,2024-01-15
1,Raju,2024-03-22,2026-05-30 14:15:20,2024-03-22 14:15:20,2500,2024,3,22,March,Friday,1,14,15,20,2024-03-22
2,Kiran,2024-06-10,2026-05-30 18:45:10,2024-06-10 18:45:10,1800,2024,6,10,June,Monday,2,18,45,10,2024-06-10
3,Suresh,2024-09-05,2026-05-30 11:20:35,2024-09-05 11:20:35,3200,2024,9,5,September,Thursday,3,11,20,35,2024-09-05
4,Lakshmi,2024-12-18,2026-05-30 22:10:05,2024-12-18 22:10:05,1500,2024,12,18,December,Wednesday,4,22,10,5,2024-12-18