<a href="https://colab.research.google.com/github/ruthikaraja08/ruthika/blob/main/employeeid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/drive/MyDrive/employee_attendance.csv")
df

  employee_name  login_date login_time  working_hours
0          Ravi  2024-02-10    8:45:30              8
1         Priya  2024-03-15    9:10:15              9
2       Karthik  2024-05-20    8:55:45              8
3        Anjali  2024-07-08    9:25:10              7
4        Vikram  2024-11-25    8:30:20              9

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_name  5 non-null      object
 1   login_date     5 non-null      object
 2   login_time     5 non-null      object
 3   working_hours  5 non-null      int64
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

In [11]:
df["login_date"]=pd.to_datetime(df["login_date"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_name  5 non-null      object
 1   login_date     5 non-null      datetime64[ns]
 2   login_time     5 non-null      object
 3   working_hours  5 non-null      int64
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 292.0+ bytes

In [12]:
df["year"]=df["login_date"].dt.year
df["month"]=df["login_date"].dt.month
df["day"]=df["login_date"].dt.day
df

  employee_name login_date login_time  working_hours  year  month  day
0          Ravi 2024-02-10    8:45:30              8  2024      2   10
1         Priya 2024-03-15    9:10:15              9  2024      3   15
2       Karthik 2024-05-20    8:55:45              8  2024      5   20
3        Anjali 2024-07-08    9:25:10              7  2024      7    8
4        Vikram 2024-11-25    8:30:20              9  2024     11   25

In [13]:
df["month_name"]=df["login_date"].dt.month_name()
df

,employee_name,login_date,login_time,working_hours,year,month,day,month_name
0,Ravi,2024-02-10,8:45:30,8,2024,2,10,February
1,Priya,2024-03-15,9:10:15,9,2024,3,15,March
2,Karthik,2024-05-20,8:55:45,8,2024,5,20,May
3,Anjali,2024-07-08,9:25:10,7,2024,7,8,July
4,Vikram,2024-11-25,8:30:20,9,2024,11,25,November

In [14]:
df["day_name"]=df["login_date"].dt.day_name()
df

,employee_name,login_date,login_time,working_hours,year,month,day,month_name,day_name
0,Ravi,2024-02-10,8:45:30,8,2024,2,10,February,Saturday
1,Priya,2024-03-15,9:10:15,9,2024,3,15,March,Friday
2,Karthik,2024-05-20,8:55:45,8,2024,5,20,May,Monday
3,Anjali,2024-07-08,9:25:10,7,2024,7,8,July,Monday
4,Vikram,2024-11-25,8:30:20,9,2024,11,25,November,Monday

In [17]:
df["hour"]=df["login_time"].dt.hour
df["minute"]=df["login_time"].dt.minute
df["seconds"]=df["login_time"].dt.second
df

AttributeError: Can only use .dt accessor with datetimelike values

In [18]:
df["login_date"].min()
df

,employee_name,login_date,login_time,working_hours,year,month,day,month_name,day_name
0,Ravi,2024-02-10,8:45:30,8,2024,2,10,February,Saturday
1,Priya,2024-03-15,9:10:15,9,2024,3,15,March,Friday
2,Karthik,2024-05-20,8:55:45,8,2024,5,20,May,Monday
3,Anjali,2024-07-08,9:25:10,7,2024,7,8,July,Monday
4,Vikram,2024-11-25,8:30:20,9,2024,11,25,November,Monday

In [19]:
df["login_date"].max()
df

,employee_name,login_date,login_time,working_hours,year,month,day,month_name,day_name
0,Ravi,2024-02-10,8:45:30,8,2024,2,10,February,Saturday
1,Priya,2024-03-15,9:10:15,9,2024,3,15,March,Friday
2,Karthik,2024-05-20,8:55:45,8,2024,5,20,May,Monday
3,Anjali,2024-07-08,9:25:10,7,2024,7,8,July,Monday
4,Vikram,2024-11-25,8:30:20,9,2024,11,25,November,Monday

In [20]:
df["working_hours"].max()

9