<a href="https://colab.research.google.com/github/ruthikaraja08/ruthika/blob/main/employeedatacleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/employee_data.csv")
df

  Employee Name   Age Department  Salary   Join Date
0          Ram   25.0         IT   50000  2023-01-15
1          Ravi   NaN         it   60000  2023/02/20
2           NaN  30.0         HR   55000  2023-03-10
3         Kumar  28.0   Finance    65000  2023-04-05
4          Ram   25.0         IT   50000  2023-01-15

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee Name  4 non-null      object
 1   Age            4 non-null      float64
 2   Department     5 non-null      object
 3   Salary         5 non-null      int64
 4   Join Date      5 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 332.0+ bytes

In [6]:
df["Age"]=df["Age"].replace(
    {
        "NaN":"Average Age"
    }
)
df

  Employee Name   Age Department  Salary   Join Date
0          Ram   25.0         IT   50000  2023-01-15
1          Ravi  27.0         it   60000  2023/02/20
2           NaN  30.0         HR   55000  2023-03-10
3         Kumar  28.0   Finance    65000  2023-04-05
4          Ram   25.0         IT   50000  2023-01-15

In [7]:
df["Employee Name"]=df["Employee Name"].replace(
    {
        "NaN":"Unknown"
    }
)
df

  Employee Name   Age Department  Salary   Join Date
0          Ram   25.0         IT   50000  2023-01-15
1          Ravi  27.0         it   60000  2023/02/20
2           NaN  30.0         HR   55000  2023-03-10
3         Kumar  28.0   Finance    65000  2023-04-05
4          Ram   25.0         IT   50000  2023-01-15

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.columns=(
    df.columns.str.lower().str.replace(" ","_")
)
df

  employee_name   age department  salary   join_date
0          Ram   25.0         IT   50000  2023-01-15
1          Ravi  27.0         it   60000  2023/02/20
2           NaN  30.0         HR   55000  2023-03-10
3         Kumar  28.0   Finance    65000  2023-04-05
4          Ram   25.0         IT   50000  2023-01-15

In [10]:
df["department"]=df["department"].replace(
    {
        "IT":"Information Technology",
        "it":"Information Technology"
    }
)
df

  employee_name   age              department  salary   join_date
0          Ram   25.0  Information Technology   50000  2023-01-15
1          Ravi  27.0  Information Technology   60000  2023/02/20
2           NaN  30.0                      HR   55000  2023-03-10
3         Kumar  28.0                Finance    65000  2023-04-05
4          Ram   25.0  Information Technology   50000  2023-01-15

In [11]:
df["join_date"]=pd.to_datetime(
    df["join_date"],
    format="mixed"
)
df

  employee_name   age              department  salary  join_date
0          Ram   25.0  Information Technology   50000 2023-01-15
1          Ravi  27.0  Information Technology   60000 2023-02-20
2           NaN  30.0                      HR   55000 2023-03-10
3         Kumar  28.0                Finance    65000 2023-04-05
4          Ram   25.0  Information Technology   50000 2023-01-15